version: "3.0"
services:
    db: 
        build:
            context: ./Docker
            dockerfile: postgres.Dockerfile
        env_file: 
            - .env.db
        expose: 
            - "5432"
        ports: 
            - 5432:5432
        volumes: 
            - db_data:/var/lib/postgresql/data
    web:
        build: 
            context: ./where_to_go
            dockerfile: ./Docker/django.Dockerfile
            args:
                DJANGO_ENV: production
        env_file:
            - ./.env
        volumes:
            - web_static:/application/static
            - web_media:/application/media
        depends_on:
            - db
    web-server:
        build:
            context: ./Docker
            dockerfile: nginx.Dockerfile
        expose:
            - "80"
        ports:
            - 80:80
        volumes:
            - web_static:/application/static
            - web_media:/application/media
        depends_on:
            - web
volumes: 
    db_data:
    web_static:
    web_media:
