version: "3.0"
services:
    web:
        build: 
            context: ./where_to_go
            dockerfile: ./Docker/web.Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - ./.env.dev
        ports:
            - 8000:8000
        volumes:
            - ./where_to_go/:/usr/src/app/
    db: 
        build:
            context: ./Docker
            dockerfile: postgres.Dockerfile
        env_file: 
            - .env.dev.db
        expose: 
            - "5432"
        ports: 
            - 5432:5432
        restart: on-failure
        volumes: 
            - dbdata:/var/lib/postgresql/data
volumes: 
    dbdata: 
