# Generated by Django 3.2.9 on 2021-11-04 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('longitude', models.FloatField(verbose_name='долгота')),
                ('langitude', models.FloatField(verbose_name='широта')),
                ('description_short', models.TextField(blank=True, verbose_name='краткое описание')),
                ('description_long', models.TextField(blank=True, verbose_name='подробное описание')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ImageField(max_length=200, upload_to='', verbose_name='имя фото места')),
                ('place', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_per_place', to='places.place')),
            ],
        ),
    ]
