# Generated by Django 3.2.9 on 2021-11-09 12:44

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_add_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('position',)},
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, verbose_name='подробное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title_short',
            field=models.CharField(blank=True, max_length=200, verbose_name='краткое название'),
        ),
    ]
