# Generated by Django 3.2.9 on 2021-11-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_add_field_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title_long',
            field=models.CharField(max_length=200, unique=True, verbose_name='подробное название'),
        ),
    ]
