# Generated by Django 3.2.9 on 2021-11-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_add_field_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_identifier',
        ),
        migrations.AddField(
            model_name='place',
            name='alias',
            field=models.CharField(blank=True, max_length=200, verbose_name='сокращение названия'),
        ),
    ]
