# Generated by Django 3.2.9 on 2021-11-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_edit_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.ImageField(upload_to='', verbose_name='имя фото места'),
        ),
    ]
