# Generated by Django 3.2.9 on 2021-12-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_delete_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='img',
        ),
    ]
